src/core/lavfindexer.cpp
As near as I can tell, matroskaindexer already does this.
=> lavfindexer: Skip unusable video tracks

configure.ac
If librtmp happens to be in the linker list, FFMS2 fails to configure because the -lrt check has a space *before* it, which also matches -lrtmp and makes the list collide with itself (``-lshine -lrtmp`` becomes ``-lshinemp``, which doesn't exist and causes the configuration error).
Since this also requires regenerating the build system, I've removed the regeneration commit from pull request #183.
=> configure.ac: fix linker collision problems from sed moving -lrt

doc/ffms2-api.md
Seems they changed stuff in the Markdown renderer and now my convenience hacks are broken.
This fixes it all, so all the inter-page links work again.
=> Update documentation to account for GitHub updates

src/core/videoutils.cpp
It has no visual effect, and it makes stuff slower, as it disables some
asm. Its main purpose is for internal swscale testing.
=> videoutils: Drop bitexact swscale flag

doc/ffms2-api.md
According to http://daringfireball.net/projects/markdown/syntax#list:
> Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab.
This applies to any block level elements nested in a list, including paragraphs, sub-lists, blockquotes, code blocks, etc. They must always be indented by at least four spaces (or one tab) for each level of
nesting.
In Debian/Ubuntu we use python-markdown and pandoc which are [not allowing](http://johnmacfarlane.net/babelmark2/?text=-+Item+1%0A++-+Item+2%0A++-+Item+3%0A-+Item+4) less than 4 spaces.
=> ffms2-api.md: Use 4-spaces indentation for sublists

src/core/lavfindexer.cpp
Speeds up indexing considerably on files with many tracks we do not index.
Also, do not set IndexMask to anything if the key doesn't exist.
=> lavfindexer: Discard any packets we don't index

src/core/ffms.cpp
I'm not entirely sure of what behavior is intended for `UseUTF8Paths` in case of multiple calls. It seems silly to even support that. Opinions?
=> Make FFMS_Init threadsafe

src/core/lavfindexer.cpp
This fixes #246.
For some reason it only affected certain formats despite being totally wrong.
I tested with VapourSynth, but not Aegisub, which should perhaps be tested.
CC: @tgoyne @myrsloik @Kagami
=> Properly discard packets during index

include/ffms.h, src/core/indexing.cpp
This can be useful for extracting information, when you don't actually
intend to decode anything.
It is written after the FFMS2 version, and the minor FFMS2 version is
bumped, so that any ffindex files with the new format won't accidentally
be opened with an older FFMS2.
Signed-off-by: Derek Buitenhuis <derek.buitenhuis@gmail.com>
=> indexing: Add an index version

src/core/videosource.cpp
See this thread: http://thread.gmane.org/gmane.comp.video.ffmpeg.devel/209921
=> videosource: Always have an alignment of 4 when allocating images

doc/ffms2-api.md, include/ffms.h, src/core/ffms.cpp, src/core/filehandle.h, src/core/indexing.cpp, src/core/indexing.h, src/core/zipfile.cpp, src/core/zipfile.h
I've tested this in my own code, as well as a hacked up copy of `ffmsindex`.
I am hardly a C++ expert, nor an expert on FFMS2's internal design, so comments, ideas, problems, etc. are very welcome.
=> [RFC] Support Reading and Writing Index in Memory

README.md
Otherwise all sorts of random branches make the badge go red.
=> README: limit the Travis badge to master branch

src/core/ffms.cpp, src/core/indexing.cpp, src/core/videoutils.cpp, src/core/videoutils.h
This is the groundwork for upcoming VP9 alt-ref and superframe support.
VP9 already has a parser inside FFmpeg, so we can't register our own, like we do for VP8, so to ready the codebase for this change, this commit separates out the VP8 "parser" into FFMS itself.
---
This needs some indexing and seeking testing visually with VP8 files before it is merged, and a good look-over by @tgoyne. #
=> indexing: Do not use a parser to determine VP8 show_frame properties

src/core/videosource.cpp
The newer API returns the rotation of the reference frame, not
the video frame.
=> lavfvideo: Adjust the use of rotation angle

doc/ffms2-changelog.md, include/ffms.h, src/core/indexing.cpp, src/core/track.cpp, src/core/track.h
When we index a format that is allowed to have discontinuous timestamps, try and break it down into distinct sections based on where the discontinuities occur, and reorder by PTS within them. We define a discontinuity as a packet timestamp difference that cannot possibly be frame reordering; in this case, more than 16 frames away, based on the duration of the first frame in the section. This probably breaks on insane VFR content. The correct way to do this is probably to fully decode, but that is a non-starter for a lot of usecases.
By default, we try and normalize the sections into fully continuous timestamps.
This adds a new field to the public FrameInfo struct to denote the original un-massaged PTS, and is thus an ABI break. It also adds a new field to the ffindex for this. The …
=> [RFC] Timestamp Discontinuity Support

doc/ffms2-api.md, doc/ffms2-changelog.md, include/ffms.h, src/core/ffms.cpp, src/index/ffmsindex.cpp, src/vapoursynth/vapoursource.cpp, src/vapoursynth/vapoursynth.cpp
Because libavformat is great, and TLS libraries are great, and network
stacks are great, libavformat has some global state init functions that
do not need to be inited, and must only be run once, and also some other
global state init functions that must be deinited upon program exit,
and reinited if used again.
To this end, I've implemented this with a lock, so it can be re-inited
after deinit safely, if the user wants to do that for some reason.
NOTE: I have not updated the AviSynth plugin to use this, since I can't figure out where the hell to put the `FFMS_Deinit()` call, because lolexceptionsforflowcontrol.
=> API: Add FFMS_Deinit

doc/ffms2-api.md, include/ffms.h, src/core/videosource.cpp, src/vapoursynth/vapoursource.cpp
This PR addresses detection of hdr and its rendering.
- The first patch is purely cosmetic, it drops the MDM prefix that carries an overly long name when spelled out, as `MDMDisplayPrimaries` would stand for `Mastering Display Metadata Display Primaries`.
- The second patch adds content light level information from ffmpeg which is also needed for hdr.
=> mastering display and content light level

doc/ffms2-api.md, include/ffms.h
these values should be returned as is from the decoder, are they validated anywhere else?
=> api: Expose matrix coefficients introduced in 2017

src/core/indexing.cpp, src/core/videosource.cpp
Otherwise, files with edit lists, for example, can have incorrect start / end times.
=> Visibility / Time Fixes

src/core/videosource.cpp, test/Makefile, test/hdr.cpp
Read AVMasteringDisplayMetadata and AVContentLightMetadata from
stream side data when present, and use it to populate VideoProperties
when frame side data is absent.
=> videosource: Support reading HDR metadata from container

src/core/track.cpp, test/tests.cpp
Should fix the keyframe mismach between `FFMS_FrameInfo` and `FFMS_Frame` in #333 discussion... not sure if it is correct, though.
@tgoyne @myrsloik maybe you remember why this used to only use OriginalPos for keyframe info? It doesn't seem right to me...
Of course, this *also* only seems to show up on edit list files... so it could be something completely different and this this **happens** to fix it. I'm a bit paranoid.
CC: @lotharkript
=> Fix Keyframe Mismach Between Info and Frame

test/hdr.cpp
The source of the values inside libavcodec/libavformat is fixed point, and using `DBL_EPSILON` is incorrect here, as well as equality.
An error of `1e-5` was chosen based off of the actual hardcoded values in the test.
=> tests/HDR: Test doubles using relative error instead of equality

Makefile.am, configure.ac, src/avisynth/avisynth.cpp, src/avisynth/avssources.cpp, src/avisynth/avssources.h
AviSynth+ can be built and used on Linux, macOS, and BSD now.
I'm not sure if I did the hook in configure.ac correctly.  I just did what the enable_debug block does.
And tbh, I'm not crazy about just define-ing __int64 to int64_t instead of doing a proper move to stdint, but it was faster and less intrusive.  I can change that if so desired.
Partially related is that -Wl,-Bsymbolic wasn't being added even if configure detected that it needed to use it.  Just a missing comma, but that's fixed here too.
=> Allow building AviSynth plugin on non-Windows

configure.ac, src/core/audiosource.cpp, src/core/indexing.cpp, src/core/indexing.h, src/core/utils.cpp, src/core/utils.h, src/core/videosource.cpp
Commits:
```
Use auto for AVCodec
The geniuses over at FFmpeg decided to constify this API, so old
versions of the library will return AVCodec *, while new versions
of the libary will return const AVCodec *, which, in C++, are not
OK to convert between.
Rather than use some macro hell in ffmscompat.h, we can work around
this by using auto.
```
```
configure: Remove deprecated API use
```
```
all: Update AVPacket API usage
AVPackets must all be on the heap now, since it is no longer
part of the libav* ABI.
```
=> FFmpeg API Shenanigans

src/core/videoutils.cpp
They changed how superframes are retured, so in older versions, they are split, and you can get a packet that contains only an invisible frame, but in newer versions, they are not split, and marking a whole superframe as invisible is incorrect.
The version was not bumped for this breaking changed, of course,, so we choose the next, unrelated version bump to check for.
This is the non-broken part from #323, and can be merged while a full fix is pending.
=> ParseVP9: Don't mark frames as invisible in newer versions of FFmpeg

src/core/videosource.cpp
Otherwise, we don't have enough packets to decode a frame until every 2nd call to GetFrame, and duplicates are output.
Not sure why I never upstreamed this.
=> videosource: Decode all packets, even if hidden, when the file is PAFF

Makefile.am, src/index/ffmsindex.cpp
Default is 1 second.
This also adds some missing `std::flush`.
=> ffmsindex: Allow adjustable progress update intervals 

include/ffms.h, src/core/videosource.cpp, src/core/videosource.h
I put this under version guards rather than bump the minimum FFmpeg version because I literally pushed this to FFmpeg master today.
=> FFMS_Frame: Pass through Dolby Vision RPU side data

src/vapoursynth/vapoursource.cpp, src/vapoursynth/vapoursource4.cpp
Normally as the RPU added in https://github.com/FFMS/ffms2/pull/396 is guarded, this has no downside.
Tested with some WIP code here: https://github.com/quietvoid/vs-placebo/blob/6bed053c32f132e477e20bd074199a31465b7c51/tonemap.c#L223
It works fine for me.
I've tested with setting an int prop to the pointer, but it does not work consistently.
Or maybe I didn't cast things properly.
=> vapoursource: Set Dolby Vision RPU data in frame props

src/core/videosource.cpp
Otherwise seeking can be jank in certain types of streams like open GOP HEVC or MP4s with huge edit list trims a the very start.
Fixes #394.
=> videosource: Only apply PAFF adjustment if the frame is marked as interlaced

src/core/videosource.cpp, src/core/videosource.h
Depending on the packet and field order, the packet which violates the delay may or may not be marked as interlaced. To 'solve' this, detect if we've ever seen an interlaced frame before.
This was broken in ff61bca13e2c5fb99c0450620c9244f415ec29c4.
=> VideoSource: Fix PAFF detection

src/core/track.cpp
=> index/track: Fudge duration of last packet if it's unknown

.github/workflows/ci.yml
Closes #411 
- ci.yml: top level permission set as contents read. Example of workflow running after change https://github.com/joycebrum/ffms2/actions/runs/4265863980
=> Set permissions for Github Workflows

src/core/indexing.cpp, src/core/utils.cpp, src/core/utils.h, src/core/videosource.cpp
If we encounter an IO error while reading packets, we don't want the current behavior of just ending the indexing or decoding here and treating the file as truncated - we want to hard fail so it is apparent there has been an IO issue.
This is helpful in e.g. networked situations.
We ($dayjob) have been using a patch similar to this internally for quite a while, so it should be pretty resilient. I finally got around to cleaning it up for submission here.
=> Hard fail on IO error during indexing and decode

Makefile.am, src/index/ffmsindex.cpp
AFAICT there's not really a sane way to split strings using the C++ STL, but maybe I am mistaken.
Also, I think the Visual C++ projects would need to be updated to link ffmsindex to libavutil? I dont have a Windows dev env, myself.
=> ffmsindex: Allow demuxer options to be set

src/core/videosource.cpp
Since https://github.com/FFmpeg/FFmpeg/commit/61b27b15fc924d7fa35baa61cfbc91568945f5db, the pointer must be initialized otherwise there is no error returned.  
And things fall apart (invalid pointers, segfault).
=> Initialize HDR10+ T35 buffer for serializing

src/core/indexing.cpp, src/core/indexing.h, src/core/track.cpp, src/core/track.h, src/core/videosource.cpp, src/core/videosource.h
This consists of various bigger refactors which were necessary to fix certain parts of seeking, but it can still mostly be read commit for commit. Some of the later commits do make some of the earlier commits partially obsolete, so let me know if you'd like any of this squashed.
I sent a patch to ffmpeg to fix 70a7c1b619105fcc6bf4ff77cc4ea34853651cd9 but didn't get a response yet.
Running seek tests with this on the [doom9 sample file collection](https://drive.google.com/file/d/1-95lSEnxu3aGZS3WqwJPaYHSk4M7GSr9/view) shows no regressions:
Before (the format being `filename,number of errors`):
```
00006.mkv,0
132518447-659caa63-ce2d-4120-9f76-5700cfc7fcb6.mov,0
3d-parrot.mkv,546
3d-parrot.MTS,547
amarec(20200806-1406)_sample.avi,0
apple_trailers.mov,0
a_test.mkv,0
AV1 Summer.webm,0
AVC …
```
=> Various fixes to seeking and decoding

configure.ac, doc/ffms2-changelog.md, include/ffms.h, src/core/videosource.cpp, src/core/videosource.h
This brings in support for decoding multi-layer video - mainly Vision Pro spatial MV-HEVC files. Only two eyes are supported.
Please comment on the API if needed.
Likely needs some refactoring, especially the inner loop.
I was lazy, so rather than doing compat stuff, I made the latest release of FFmpeg (7.1) the minimum.
CC: @arch1t3cht (because you probably Have Opinions)
=> Multilayer Decoding Support (and minimum FFmpeg version bump)

autogen.sh
Don't force the user to run configure.
A lot of tool use this variable:
- https://github.com/adah1972/libunibreak/blob/master/autogen.sh#L12-L16
- https://github.com/fribidi/fribidi/blob/master/autogen.sh#L32-L35
- https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/main/autogen.sh?ref_type=heads#L120-126
=> [autogen.sh] Add NOCONFIGURE

README.md
We replaced travis CI with github action a long time ago.
The documentation of the badge is available here: https://docs.github.com/en/actions/how-tos/monitor-workflows/add-a-status-badge
=> [README.md] Replace travis CI link with github action

version.sh
Previously, echo_maybe() exited with code 1. This caused the script to signal an error even though version detection succeeded.
I just changed the exit code from 1 to 0 to indicate success when a version is found.
=> [version.sh] Return success when version is found
